# Generated by Django 5.1.3 on 2024-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_learn_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learn",
            name="content",
            field=models.TextField(max_length=600),
        ),
    ]
