# Generated by Django 5.1.3 on 2024-11-09 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Closed", "Closed"),
                            ("In Progress", "In Progress"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Criminal", "Criminal"),
                            ("Family", "Family"),
                            ("Corporate", "Corporate"),
                            ("Intellectual Property", "Intellectual Property"),
                            ("Immigration", "Immigration"),
                            ("Labor", "Labor"),
                            ("Real Estate", "Real Estate"),
                            ("Tax", "Tax"),
                            ("Environmental", "Environmental"),
                            ("Health", "Health"),
                            ("Human Rights", "Human Rights"),
                            ("Contract", "Contract"),
                            ("International", "International"),
                        ],
                        default="Criminal",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload a document related to the case",
                        upload_to="case_documents/",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Name of the document", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="bono.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Criminal Law", "Criminal Law"),
                            ("Family Law", "Family Law"),
                            ("Corporate Law", "Corporate Law"),
                            ("Intellectual Property", "Intellectual Property"),
                            ("Immigration Law", "Immigration Law"),
                            ("Labor Law", "Labor Law"),
                            ("Real Estate Law", "Real Estate Law"),
                            ("Tax Law", "Tax Law"),
                            ("Environmental Law", "Environmental Law"),
                            ("Health Law", "Health Law"),
                            ("Human Rights Law", "Human Rights Law"),
                            ("Contract Law", "Contract Law"),
                            ("International Law", "International Law"),
                        ],
                        default="General Practice",
                        max_length=255,
                    ),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile image for the lawyer",
                        null=True,
                        upload_to="lawyer_images/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="bono.case",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="bono.lawyer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="bono.posttopic",
                    ),
                ),
            ],
        ),
    ]
